proxy:
  host: "127.0.0.1"
  port: 19122
destination:
  host: "127.0.0.1"
  port: 19132
max-homes: 2
pass-through: true
log-packets: true
spawn-coords:
  x: 0.0
  y: 0.0
  z: 0.0
permissions: {}
home-list: {}
ignored-packets:

tpa-timeout: 30
tp-time: 5
